feat(tool): setup codecov flags configuration
jld3103/nextcloud-neon pull request #1774
Opened 2024-03-14 22:02 UTC by Leptopoda

finally closes: #910 
Sadly we need to add every package to the codecov config.
I've tested it in my fork and it works (coverage is correctly displayed in the codecov panel.
Coverage will only be added over time when each package first runs its tests.

@provokateurin did you already add the CI token to the github secrets? I don't have access to that so I couldn't check myself.

2024-03-14 22:25 UTC, provokateurin commented
I didn't add the token yet

2024-03-14 22:26 UTC, provokateurin commented on tool/update-codecov-config.sh
It would be better to always generate the full config every time. Right now if we would remove a package it wouldn't be removed from the config. Also you only update the path and never create the parent elements, so I think it will fail if we have a new package.

2024-03-15 10:11 UTC, Leptopoda commented on tool/update-codecov-config.sh
It wouldn't fail.
I just added a call to jq dropping the flags before regenerating

2024-03-15 10:27 UTC, provokateurin requested changes
Is it possible to trigger all tests in this PR to see that it is working?

2024-03-15 10:27 UTC, provokateurin commented on tool/update-codecov-config.sh
> +#set -euxo pipefail
```suggestion
set -euxo pipefail
```

2024-03-15 10:27 UTC, provokateurin commented on tool/update-codecov-config.sh
The workflow of adding a new package needs to be adjusted so people know they need to run this script.

2024-03-15 10:29 UTC, provokateurin commented
I just added the token to the secrets so it should work.

2024-03-15 11:04 UTC, provokateurin requested changes
Ok looks like this works correctly. Please add the documentation and revert the test commit, then this can be merged

2024-03-15 11:18 UTC, provokateurin approved these changes

2024-03-15 11:31 UTC, provokateurin commented
@Leptopoda Merge?

2024-03-15 11:50 UTC, merged